###Cadastrar funcionario
POST http://localhost:3000/funcionario/cadastrar
Content-Type: application/json

{
    "nome":"Tomas",
    "cpf":"135.410.690-31",
    "sexo":"MASCULINO",
    "senha":"321"
}

###Listar funcionario
GET http://localhost:3000/funcionario/listar

###Buscar funcionario por id
GET http://localhost:3000/funcionario/buscar/60907504d31bfa22f4f525f3

###Remover funcionario
GET http://localhost:3000/funcionario/remover/60907504d31bfa22f4f525f3

###Alterar funcionario
POST http://localhost:3000/funcionario/alterar
Content-Type: application/json

{
    "_id":"6090735ed31bfa22f4f525f2",
    "nome":"Alice",
    "cpf":"583.122.400-71",
    "sexo":"FEMININO",
    "senha":"321"
}

###Login funcionario
POST http://localhost:3000/funcionario/login
Content-Type: application/json

{
    "cpf":"583.122.400-71",
    "senha":"321"
}

###Logout funcionario
GET http://localhost:3000/funcionario/logout
