###Cadastrar usuario
POST http://localhost:3000/usuario/cadastrar
Content-Type: application/json

{
    "nome":"Marcia",
    "cpf":"095.632.635-25",
    "sexo":"FEMININO",
    "senha":"35460"
}

###Listar usuario
GET http://localhost:3000/usuario/listar

###Buscar usuario por id
GET http://localhost:3000/usuario/buscar/60dc778d3890a304141df22b

###Remover usuario
DELETE http://localhost:3000/usuario/remover/60dc778d3890a304141df22b

###Alterar usuario
PUT http://localhost:3000/usuario/alterar
Content-Type: application/json

{
    "_id":"60dc778d3890a304141df22b",
    "nome":"Alice",
    "cpf":"516.868.520-02",
    "sexo":"FEMININO",
    "senha":"abc"
}


###Login usuario
POST http://localhost:3000/usuario/login
Content-Type: application/json

{
    "cpf":"516.868.520-02",
    "senha":"321"
}

###Login usuario
POST http://localhost:3000/usuario/login
Content-Type: application/json

{
    "cpf":"466.488.450-82",
    "senha":"123123"
}

###Logout usuario
GET http://localhost:3000/usuario/logout
