###Cadastrar funcionario
POST http://localhost:3000/funcionario/cadastrar
Content-Type: application/json

{
    "nome":"Tomas",
    "cpf":"135.410.690-31",
    "sexo":"MASCULINO",
    "senha":"321"
}

###Listar funcionario
GET http://localhost:3000/funcionario/listar

###Buscar funcionario por id
GET http://localhost:3000/funcionario/buscar/60950c1a10e9e61eb0c70ca8

###Remover funcionario
GET http://localhost:3000/funcionario/remover/60950c1a10e9e61eb0c70ca8

###Alterar funcionario
POST http://localhost:3000/funcionario/alterar
Content-Type: application/json

{
    "_id":"609513875448ff28c83c324b",
    "nome":"Alice",
    "cpf":"135.410.690-31",
    "sexo":"FEMININO",
    "hash":"321"
}

###Login funcionario
POST http://localhost:3000/funcionario/login
Content-Type: application/json

{
    "cpf":"135.410.690-31",
    "senha":"321"
}

###Logout funcionario
GET http://localhost:3000/funcionario/logout
