###Cadastrar usuario
POST http://localhost:3000/usuario/cadastrar
Content-Type: application/json

{
    "nome":"Fernando",
    "cpf":"466.488.450-82",
    "sexo":"MASCULINO",
    "senha":"123123",
    "emprestimos":[]
}

###Listar usuario
GET http://localhost:3000/usuario/listar

###Buscar usuario por id
GET http://localhost:3000/usuario/buscar/60950be810e9e61eb0c70ca6

###Remover usuario
GET http://localhost:3000/usuario/remover/60950be810e9e61eb0c70ca6

###Alterar usuario
POST http://localhost:3000/usuario/alterar
Content-Type: application/json

{
    "_id":"60a2db1171e57921d46cfd08",
    "nome":"Alice",
    "cpf":"516.868.520-02",
    "sexo":"FEMININO",
    "senha":"321"
}


###Login usuario
POST http://localhost:3000/usuario/login
Content-Type: application/json

{
    "cpf":"516.868.520-02",
    "senha":"321"
}

###Login usuario
POST http://localhost:3000/usuario/login
Content-Type: application/json

{
    "cpf":"466.488.450-82",
    "senha":"123123"
}

###Logout usuario
GET http://localhost:3000/usuario/logout
