
POST http://localhost:3000/usuario/cadastrar
Content-Type: application/json

{
    "nome":"Alice",
    "cpf":"224.414.180-25",
    "sexo":"FEMININO"
}

###
GET http://localhost:3000/usuario/listar

###
GET http://localhost:3000/usuario/buscar/6089dcd465ecbb21bc897d54

###
GET http://localhost:3000/usuario/remover/6089dcd465ecbb21bc897d54

###
POST http://localhost:3000/usuario/alterar
Content-Type: application/json

{
    "_id":"608beff895fde72df44e6c78",
    "nome":"Alice",
    "cpf":"516.868.520-02",
    "sexo":"FEMININO"
}